name: CICD 

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: PROD
        

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Docker login
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              run: docker build -t echoech0/nodeapp .

            - name: Publish Image to docker hub
              run: docker push echoech0/nodeapp:latest


    deploy:
        needs: build
        runs-on: aws-ec2
        environment: PROD
        steps:
            - name: Pull docker image
              run: docker pull echoech0/nodeapp:latest

            - name: Delete old container
              run: docker rm -f nodeContainer
            
            - name: Run docker container
              run: docker run -d -p 5000:5000 --name nodeContainer echoech0/nodeapp

            - name: Creating .env file
              run: |
                  docker exec -it nodeContainer /bin/sh
                  touch .env
                  echo "${{secrets.MY_ENVIRONMENT}}" > .env

            - name: Restarting Docker Container
              run: docker restart nodeContainer
            